# Generated by Django 5.1.4 on 2025-01-18 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100)),
                ('proficiency', models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Native', 'Native')], default='Basic', max_length=50)),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='crudoncv.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='crudoncv.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='crudoncv.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='crudoncv.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='crudoncv.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='crudoncv.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='crudoncv.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('personal_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='crudoncv.personaldetails')),
            ],
        ),
    ]
