# Generated by Django 5.1.4 on 2025-01-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudoncv', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='achievement',
            constraint=models.UniqueConstraint(fields=('personal_details', 'title', 'date'), name='unique_achievement_per_user'),
        ),
        migrations.AddConstraint(
            model_name='education',
            constraint=models.UniqueConstraint(fields=('personal_details', 'institution', 'degree'), name='unique_education_per_user'),
        ),
        migrations.AddConstraint(
            model_name='experience',
            constraint=models.UniqueConstraint(fields=('personal_details', 'company', 'position', 'duration'), name='unique_experience_per_user'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(fields=('personal_details', 'language_name', 'proficiency'), name='unique_language_per_user'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('personal_details', 'project_name'), name='unique_project_per_user'),
        ),
        migrations.AddConstraint(
            model_name='reference',
            constraint=models.UniqueConstraint(fields=('personal_details', 'name', 'relationship'), name='unique_reference_per_user'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('personal_details', 'skill_name'), name='unique_skill_per_user'),
        ),
        migrations.AddConstraint(
            model_name='training',
            constraint=models.UniqueConstraint(fields=('personal_details', 'training_name', 'organization'), name='unique_training_per_user'),
        ),
    ]
